NVAPI Reference Documentation
NVAPI Reference Documentation
NVIDIA
Release 440: November 15
2019
nvHLSLExtns.h File Reference
#include "nvHLSLExtnsInternal.h"
Functions
int NvShfl (int val, uint srcLane, int width=NV_WARP_SIZE)
int2 NvShfl (int2 val, uint srcLane, int width=NV_WARP_SIZE)
int4 NvShfl (int4 val, uint srcLane, int width=NV_WARP_SIZE)
int NvShflUp (int val, uint delta, int width=NV_WARP_SIZE)
int NvShflDown (int val, uint delta, int width=NV_WARP_SIZE)
int NvShflXor (int val, uint laneMask, int width=NV_WARP_SIZE)
uint NvAny (int predicate)
uint NvAll (int predicate)
uint NvBallot (int predicate)
int NvGetLaneId ()
uint NvGetSpecial (uint subOpCode)
uint NvInterlockedAddFp16x2 (RWByteAddressBuffer uav, uint byteAddress, uint fp16x2Val)
uint NvInterlockedMinFp16x2 (RWByteAddressBuffer uav, uint byteAddress, uint fp16x2Val)
uint NvInterlockedMaxFp16x2 (RWByteAddressBuffer uav, uint byteAddress, uint fp16x2Val)
uint NvInterlockedAddFp16x2 (RWByteAddressBuffer uav, uint byteAddress, float2 val)
uint NvInterlockedMinFp16x2 (RWByteAddressBuffer uav, uint byteAddress, float2 val)
uint NvInterlockedMaxFp16x2 (RWByteAddressBuffer uav, uint byteAddress, float2 val)
uint NvInterlockedAddFp16x2 (RWTexture1D< float2 > uav, uint address, uint fp16x2Val)
uint NvInterlockedMinFp16x2 (RWTexture1D< float2 > uav, uint address, uint fp16x2Val)
uint NvInterlockedMaxFp16x2 (RWTexture1D< float2 > uav, uint address, uint fp16x2Val)
uint NvInterlockedAddFp16x2 (RWTexture2D< float2 > uav, uint2 address, uint fp16x2Val)
uint NvInterlockedMinFp16x2 (RWTexture2D< float2 > uav, uint2 address, uint fp16x2Val)
uint NvInterlockedMaxFp16x2 (RWTexture2D< float2 > uav, uint2 address, uint fp16x2Val)
uint NvInterlockedAddFp16x2 (RWTexture3D< float2 > uav, uint3 address, uint fp16x2Val)
uint NvInterlockedMinFp16x2 (RWTexture3D< float2 > uav, uint3 address, uint fp16x2Val)
uint NvInterlockedMaxFp16x2 (RWTexture3D< float2 > uav, uint3 address, uint fp16x2Val)
uint NvInterlockedAddFp16x2 (RWTexture1D< float2 > uav, uint address, float2 val)
uint NvInterlockedMinFp16x2 (RWTexture1D< float2 > uav, uint address, float2 val)
uint NvInterlockedMaxFp16x2 (RWTexture1D< float2 > uav, uint address, float2 val)
uint NvInterlockedAddFp16x2 (RWTexture2D< float2 > uav, uint2 address, float2 val)
uint NvInterlockedMinFp16x2 (RWTexture2D< float2 > uav, uint2 address, float2 val)
uint NvInterlockedMaxFp16x2 (RWTexture2D< float2 > uav, uint2 address, float2 val)
uint NvInterlockedAddFp16x2 (RWTexture3D< float2 > uav, uint3 address, float2 val)
uint NvInterlockedMinFp16x2 (RWTexture3D< float2 > uav, uint3 address, float2 val)
uint NvInterlockedMaxFp16x2 (RWTexture3D< float2 > uav, uint3 address, float2 val)
uint2 NvInterlockedAddFp16x4 (RWTexture1D< float4 > uav, uint address, uint2 fp16x2Val)
uint2 NvInterlockedMinFp16x4 (RWTexture1D< float4 > uav, uint address, uint2 fp16x2Val)
uint2 NvInterlockedMaxFp16x4 (RWTexture1D< float4 > uav, uint address, uint2 fp16x2Val)
uint2 NvInterlockedAddFp16x4 (RWTexture2D< float4 > uav, uint2 address, uint2 fp16x2Val)
uint2 NvInterlockedMinFp16x4 (RWTexture2D< float4 > uav, uint2 address, uint2 fp16x2Val)
uint2 NvInterlockedMaxFp16x4 (RWTexture2D< float4 > uav, uint2 address, uint2 fp16x2Val)
uint2 NvInterlockedAddFp16x4 (RWTexture3D< float4 > uav, uint3 address, uint2 fp16x2Val)
uint2 NvInterlockedMinFp16x4 (RWTexture3D< float4 > uav, uint3 address, uint2 fp16x2Val)
uint2 NvInterlockedMaxFp16x4 (RWTexture3D< float4 > uav, uint3 address, uint2 fp16x2Val)
uint2 NvInterlockedAddFp16x4 (RWTexture1D< float4 > uav, uint address, float4 val)
uint2 NvInterlockedMinFp16x4 (RWTexture1D< float4 > uav, uint address, float4 val)
uint2 NvInterlockedMaxFp16x4 (RWTexture1D< float4 > uav, uint address, float4 val)
uint2 NvInterlockedAddFp16x4 (RWTexture2D< float4 > uav, uint2 address, float4 val)
uint2 NvInterlockedMinFp16x4 (RWTexture2D< float4 > uav, uint2 address, float4 val)
uint2 NvInterlockedMaxFp16x4 (RWTexture2D< float4 > uav, uint2 address, float4 val)
uint2 NvInterlockedAddFp16x4 (RWTexture3D< float4 > uav, uint3 address, float4 val)
uint2 NvInterlockedMinFp16x4 (RWTexture3D< float4 > uav, uint3 address, float4 val)
uint2 NvInterlockedMaxFp16x4 (RWTexture3D< float4 > uav, uint3 address, float4 val)
float NvInterlockedAddFp32 (RWByteAddressBuffer uav, uint byteAddress, float val)
float NvInterlockedAddFp32 (RWTexture1D< float > uav, uint address, float val)
float NvInterlockedAddFp32 (RWTexture2D< float > uav, uint2 address, float val)
float NvInterlockedAddFp32 (RWTexture3D< float > uav, uint3 address, float val)
uint2 NvInterlockedAddUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
uint2 NvInterlockedMaxUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
uint2 NvInterlockedMinUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
uint2 NvInterlockedAndUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
uint2 NvInterlockedOrUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
uint2 NvInterlockedXorUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
uint2 NvInterlockedCompareExchangeUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 compare_value, uint2 value)
uint2 NvInterlockedExchangeUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
uint2 NvInterlockedAddUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
uint2 NvInterlockedMaxUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
uint2 NvInterlockedMinUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
uint2 NvInterlockedAndUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
uint2 NvInterlockedOrUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
uint2 NvInterlockedXorUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
uint2 NvInterlockedCompareExchangeUint64 (RWTexture1D< uint2 > uav, uint address, uint2 compare_value, uint2 value)
uint2 NvInterlockedExchangeUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
uint2 NvInterlockedAddUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
uint2 NvInterlockedMaxUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
uint2 NvInterlockedMinUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
uint2 NvInterlockedAndUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
uint2 NvInterlockedOrUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
uint2 NvInterlockedXorUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
uint2 NvInterlockedCompareExchangeUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 compare_value, uint2 value)
uint2 NvInterlockedExchangeUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
uint2 NvInterlockedAddUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
uint2 NvInterlockedMaxUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
uint2 NvInterlockedMinUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
uint2 NvInterlockedAndUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
uint2 NvInterlockedOrUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
uint2 NvInterlockedXorUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
uint2 NvInterlockedCompareExchangeUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 compare_value, uint2 value)
uint2 NvInterlockedExchangeUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
uint3 NvGetShadingRate ()
float NvEvaluateAttributeAtSampleForVPRS (float attrib, uint sampleIndex, int2 pixelOffset)
float2 NvEvaluateAttributeAtSampleForVPRS (float2 attrib, uint sampleIndex, int2 pixelOffset)
float3 NvEvaluateAttributeAtSampleForVPRS (float3 attrib, uint sampleIndex, int2 pixelOffset)
float4 NvEvaluateAttributeAtSampleForVPRS (float4 attrib, uint sampleIndex, int2 pixelOffset)
int NvEvaluateAttributeAtSampleForVPRS (int attrib, uint sampleIndex, int2 pixelOffset)
int2 NvEvaluateAttributeAtSampleForVPRS (int2 attrib, uint sampleIndex, int2 pixelOffset)
int3 NvEvaluateAttributeAtSampleForVPRS (int3 attrib, uint sampleIndex, int2 pixelOffset)
int4 NvEvaluateAttributeAtSampleForVPRS (int4 attrib, uint sampleIndex, int2 pixelOffset)
uint NvEvaluateAttributeAtSampleForVPRS (uint attrib, uint sampleIndex, int2 pixelOffset)
uint2 NvEvaluateAttributeAtSampleForVPRS (uint2 attrib, uint sampleIndex, int2 pixelOffset)
uint3 NvEvaluateAttributeAtSampleForVPRS (uint3 attrib, uint sampleIndex, int2 pixelOffset)
uint4 NvEvaluateAttributeAtSampleForVPRS (uint4 attrib, uint sampleIndex, int2 pixelOffset)
float NvEvaluateAttributeSnappedForVPRS (float attrib, uint2 offset)
float2 NvEvaluateAttributeSnappedForVPRS (float2 attrib, uint2 offset)
float3 NvEvaluateAttributeSnappedForVPRS (float3 attrib, uint2 offset)
float4 NvEvaluateAttributeSnappedForVPRS (float4 attrib, uint2 offset)
int NvEvaluateAttributeSnappedForVPRS (int attrib, uint2 offset)
int2 NvEvaluateAttributeSnappedForVPRS (int2 attrib, uint2 offset)
int3 NvEvaluateAttributeSnappedForVPRS (int3 attrib, uint2 offset)
int4 NvEvaluateAttributeSnappedForVPRS (int4 attrib, uint2 offset)
uint NvEvaluateAttributeSnappedForVPRS (uint attrib, uint2 offset)
uint2 NvEvaluateAttributeSnappedForVPRS (uint2 attrib, uint2 offset)
uint3 NvEvaluateAttributeSnappedForVPRS (uint3 attrib, uint2 offset)
uint4 NvEvaluateAttributeSnappedForVPRS (uint4 attrib, uint2 offset)
uint NvWaveMatch (uint value)
uint NvWaveMatch (uint2 value)
uint NvWaveMatch (uint4 value)
uint NvWaveMatch (float value)
uint NvWaveMatch (float2 value)
uint NvWaveMatch (float4 value)
uint4 NvFootprintFine (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, int3 offset=int3(0, 0, 0))
uint4 NvFootprintCoarse (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, int3 offset=int3(0, 0, 0))
uint4 NvFootprintFineBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float bias, int3 offset=int3(0, 0, 0))
uint4 NvFootprintCoarseBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float bias, int3 offset=int3(0, 0, 0))
uint4 NvFootprintFineLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float lodLevel, int3 offset=int3(0, 0, 0))
uint4 NvFootprintCoarseLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float lodLevel, int3 offset=int3(0, 0, 0))
uint4 NvFootprintFineGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float3 ddx, float3 ddy, int3 offset=int3(0, 0, 0))
uint4 NvFootprintCoarseGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float3 ddx, float3 ddy, int3 offset=int3(0, 0, 0))
uint NvFootprintExtractLOD (uint4 blob)
uint NvFootprintExtractReturnGran (uint4 blob)
uint2 NvFootprintExtractAnchorTileLoc2D (uint4 blob)
uint3 NvFootprintExtractAnchorTileLoc3D (uint4 blob)
uint2 NvFootprintExtractOffset2D (uint4 blob)
uint3 NvFootprintExtractOffset3D (uint4 blob)
uint2 NvFootprintExtractBitmask (uint4 blob)
uint4 NvFootprintFine (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, out uint isSingleLod, int3 offset=int3(0, 0, 0))
uint4 NvFootprintCoarse (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, out uint isSingleLod, int3 offset=int3(0, 0, 0))
uint4 NvFootprintFineBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float bias, out uint isSingleLod, int3 offset=int3(0, 0, 0))
uint4 NvFootprintCoarseBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float bias, out uint isSingleLod, int3 offset=int3(0, 0, 0))
uint4 NvFootprintFineLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float lodLevel, out uint isSingleLod, int3 offset=int3(0, 0, 0))
uint4 NvFootprintCoarseLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float lodLevel, out uint isSingleLod, int3 offset=int3(0, 0, 0))
uint4 NvFootprintFineGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float3 ddx, float3 ddy, out uint isSingleLod, int3 offset=int3(0, 0, 0))
uint4 NvFootprintCoarseGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float3 ddx, float3 ddy, out uint isSingleLod, int3 offset=int3(0, 0, 0))
uint NvActiveThreads ()
uint NvWaveMultiPrefixInclusiveAdd (uint val, uint mask)
uint NvWaveMultiPrefixExclusiveAdd (uint val, uint mask)
uint2 NvWaveMultiPrefixInclusiveAdd (uint2 val, uint mask)
uint2 NvWaveMultiPrefixExclusiveAdd (uint2 val, uint mask)
uint4 NvWaveMultiPrefixInclusiveAdd (uint4 val, uint mask)
uint4 NvWaveMultiPrefixExclusiveAdd (uint4 val, uint mask)
uint NvWaveMultiPrefixInclusiveAnd (uint val, uint mask)
uint NvWaveMultiPrefixExclusiveAnd (uint val, uint mask)
uint2 NvWaveMultiPrefixInclusiveAnd (uint2 val, uint mask)
uint2 NvWaveMultiPrefixExclusiveAnd (uint2 val, uint mask)
uint4 NvWaveMultiPrefixInclusiveAnd (uint4 val, uint mask)
uint4 NvWaveMultiPrefixExclusiveAnd (uint4 val, uint mask)
uint NvWaveMultiPrefixInclusiveOr (uint val, uint mask)
uint NvWaveMultiPrefixExclusiveOr (uint val, uint mask)
uint2 NvWaveMultiPrefixInclusiveOr (uint2 val, uint mask)
uint2 NvWaveMultiPrefixExclusiveOr (uint2 val, uint mask)
uint4 NvWaveMultiPrefixInclusiveOr (uint4 val, uint mask)
uint4 NvWaveMultiPrefixExclusiveOr (uint4 val, uint mask)
uint NvWaveMultiPrefixInclusiveXOr (uint val, uint mask)
uint NvWaveMultiPrefixExclusiveXOr (uint val, uint mask)
uint2 NvWaveMultiPrefixInclusiveXOr (uint2 val, uint mask)
uint2 NvWaveMultiPrefixExclusiveXOr (uint2 val, uint mask)
uint4 NvWaveMultiPrefixInclusiveXOr (uint4 val, uint mask)
uint4 NvWaveMultiPrefixExclusiveXOr (uint4 val, uint mask)
Function Documentation
uint NvActiveThreads ()
References NvBallot().
Referenced by NvWaveMultiPrefixExclusiveAdd(), NvWaveMultiPrefixExclusiveAnd(), NvWaveMultiPrefixExclusiveOr(), NvWaveMultiPrefixExclusiveXOr(), NvWaveMultiPrefixInclusiveAdd(), NvWaveMultiPrefixInclusiveAnd(), NvWaveMultiPrefixInclusiveOr(), and NvWaveMultiPrefixInclusiveXOr().
uint NvAll (int predicate)
References g_NvidiaExt, and NV_EXTN_OP_VOTE_ALL.
uint NvAny (int predicate)
References g_NvidiaExt, and NV_EXTN_OP_VOTE_ANY.
uint NvBallot (int predicate)
References g_NvidiaExt, and NV_EXTN_OP_VOTE_BALLOT.
Referenced by NvActiveThreads().
float NvEvaluateAttributeAtSampleForVPRS (float attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
float2 NvEvaluateAttributeAtSampleForVPRS (float2 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
float3 NvEvaluateAttributeAtSampleForVPRS (float3 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
float4 NvEvaluateAttributeAtSampleForVPRS (float4 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
int NvEvaluateAttributeAtSampleForVPRS (int attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
int2 NvEvaluateAttributeAtSampleForVPRS (int2 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
int3 NvEvaluateAttributeAtSampleForVPRS (int3 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
int4 NvEvaluateAttributeAtSampleForVPRS (int4 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
uint NvEvaluateAttributeAtSampleForVPRS (uint attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
uint2 NvEvaluateAttributeAtSampleForVPRS (uint2 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
uint3 NvEvaluateAttributeAtSampleForVPRS (uint3 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
uint4 NvEvaluateAttributeAtSampleForVPRS (uint4 attrib, uint sampleIndex, int2 pixelOffset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_AT_SAMPLE.
float NvEvaluateAttributeSnappedForVPRS (float attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
float2 NvEvaluateAttributeSnappedForVPRS (float2 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
float3 NvEvaluateAttributeSnappedForVPRS (float3 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
float4 NvEvaluateAttributeSnappedForVPRS (float4 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
int NvEvaluateAttributeSnappedForVPRS (int attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
int2 NvEvaluateAttributeSnappedForVPRS (int2 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
int3 NvEvaluateAttributeSnappedForVPRS (int3 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
int4 NvEvaluateAttributeSnappedForVPRS (int4 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
uint NvEvaluateAttributeSnappedForVPRS (uint attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
uint2 NvEvaluateAttributeSnappedForVPRS (uint2 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
uint3 NvEvaluateAttributeSnappedForVPRS (uint3 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
uint4 NvEvaluateAttributeSnappedForVPRS (uint4 attrib, uint2 offset)
References g_NvidiaExt, and NV_EXTN_OP_VPRS_EVAL_ATTRIB_SNAPPED.
uint4 NvFootprintCoarse (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, int3 offset = int3(0, 0, 0))
References __NvFootprint(), and NV_EXTN_FOOTPRINT_MODE_COARSE.
uint4 NvFootprintCoarse (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, out uint isSingleLod, int3 offset = int3(0, 0, 0))
References __NvFootprint(), __NvGetSpecial(), NV_EXTN_FOOTPRINT_MODE_COARSE, and NV_SPECIALOP_FOOTPRINT_SINGLELOD_PRED.
uint4 NvFootprintCoarseBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float bias, int3 offset = int3(0, 0, 0))
References __NvFootprintBias(), and NV_EXTN_FOOTPRINT_MODE_COARSE.
uint4 NvFootprintCoarseBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float bias, out uint isSingleLod, int3 offset = int3(0, 0, 0))
References __NvFootprintBias(), __NvGetSpecial(), NV_EXTN_FOOTPRINT_MODE_COARSE, and NV_SPECIALOP_FOOTPRINT_SINGLELOD_PRED.
uint4 NvFootprintCoarseGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float3 ddx, float3 ddy, int3 offset = int3(0, 0, 0))
References __NvFootprintGrad(), and NV_EXTN_FOOTPRINT_MODE_COARSE.
uint4 NvFootprintCoarseGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float3 ddx, float3 ddy, out uint isSingleLod, int3 offset = int3(0, 0, 0))
References __NvFootprintGrad(), __NvGetSpecial(), NV_EXTN_FOOTPRINT_MODE_COARSE, and NV_SPECIALOP_FOOTPRINT_SINGLELOD_PRED.
uint4 NvFootprintCoarseLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float lodLevel, int3 offset = int3(0, 0, 0))
References __NvFootprintLevel(), and NV_EXTN_FOOTPRINT_MODE_COARSE.
uint4 NvFootprintCoarseLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float lodLevel, out uint isSingleLod, int3 offset = int3(0, 0, 0))
References __NvFootprintLevel(), __NvGetSpecial(), NV_EXTN_FOOTPRINT_MODE_COARSE, and NV_SPECIALOP_FOOTPRINT_SINGLELOD_PRED.
uint2 NvFootprintExtractAnchorTileLoc2D (uint4 blob)
uint3 NvFootprintExtractAnchorTileLoc3D (uint4 blob)
uint2 NvFootprintExtractBitmask (uint4 blob)
uint NvFootprintExtractLOD (uint4 blob)
uint2 NvFootprintExtractOffset2D (uint4 blob)
uint3 NvFootprintExtractOffset3D (uint4 blob)
uint NvFootprintExtractReturnGran (uint4 blob)
uint4 NvFootprintFine (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, int3 offset = int3(0, 0, 0))
References __NvFootprint(), and NV_EXTN_FOOTPRINT_MODE_FINE.
uint4 NvFootprintFine (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, out uint isSingleLod, int3 offset = int3(0, 0, 0))
References __NvFootprint(), __NvGetSpecial(), NV_EXTN_FOOTPRINT_MODE_FINE, and NV_SPECIALOP_FOOTPRINT_SINGLELOD_PRED.
uint4 NvFootprintFineBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float bias, int3 offset = int3(0, 0, 0))
References __NvFootprintBias(), and NV_EXTN_FOOTPRINT_MODE_FINE.
uint4 NvFootprintFineBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float bias, out uint isSingleLod, int3 offset = int3(0, 0, 0))
References __NvFootprintBias(), __NvGetSpecial(), NV_EXTN_FOOTPRINT_MODE_FINE, and NV_SPECIALOP_FOOTPRINT_SINGLELOD_PRED.
uint4 NvFootprintFineGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float3 ddx, float3 ddy, int3 offset = int3(0, 0, 0))
References __NvFootprintGrad(), and NV_EXTN_FOOTPRINT_MODE_FINE.
uint4 NvFootprintFineGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float3 ddx, float3 ddy, out uint isSingleLod, int3 offset = int3(0, 0, 0))
References __NvFootprintGrad(), __NvGetSpecial(), NV_EXTN_FOOTPRINT_MODE_FINE, and NV_SPECIALOP_FOOTPRINT_SINGLELOD_PRED.
uint4 NvFootprintFineLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float lodLevel, int3 offset = int3(0, 0, 0))
References __NvFootprintLevel(), and NV_EXTN_FOOTPRINT_MODE_FINE.
uint4 NvFootprintFineLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint gran, float lodLevel, out uint isSingleLod, int3 offset = int3(0, 0, 0))
References __NvFootprintLevel(), __NvGetSpecial(), NV_EXTN_FOOTPRINT_MODE_FINE, and NV_SPECIALOP_FOOTPRINT_SINGLELOD_PRED.
int NvGetLaneId ()
References g_NvidiaExt, and NV_EXTN_OP_GET_LANE_ID.
uint3 NvGetShadingRate ()
References g_NvidiaExt, and NV_EXTN_OP_GET_SHADING_RATE.
uint NvGetSpecial (uint subOpCode)
References __NvGetSpecial().
uint NvInterlockedAddFp16x2 (RWByteAddressBuffer uav, uint byteAddress, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint NvInterlockedAddFp16x2 (RWByteAddressBuffer uav, uint byteAddress, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint NvInterlockedAddFp16x2 (RWTexture1D< float2 > uav, uint address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint NvInterlockedAddFp16x2 (RWTexture2D< float2 > uav, uint2 address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint NvInterlockedAddFp16x2 (RWTexture3D< float2 > uav, uint3 address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint NvInterlockedAddFp16x2 (RWTexture1D< float2 > uav, uint address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint NvInterlockedAddFp16x2 (RWTexture2D< float2 > uav, uint2 address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint NvInterlockedAddFp16x2 (RWTexture3D< float2 > uav, uint3 address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddFp16x4 (RWTexture1D< float4 > uav, uint address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddFp16x4 (RWTexture2D< float4 > uav, uint2 address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddFp16x4 (RWTexture3D< float4 > uav, uint3 address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddFp16x4 (RWTexture1D< float4 > uav, uint address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddFp16x4 (RWTexture2D< float4 > uav, uint2 address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddFp16x4 (RWTexture3D< float4 > uav, uint3 address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_ADD.
float NvInterlockedAddFp32 (RWByteAddressBuffer uav, uint byteAddress, float val)
References __NvAtomicAddFP32().
float NvInterlockedAddFp32 (RWTexture1D< float > uav, uint address, float val)
References __NvAtomicAddFP32().
float NvInterlockedAddFp32 (RWTexture2D< float > uav, uint2 address, float val)
References __NvAtomicAddFP32().
float NvInterlockedAddFp32 (RWTexture3D< float > uav, uint3 address, float val)
References __NvAtomicAddFP32().
uint2 NvInterlockedAddUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAddUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_ADD.
uint2 NvInterlockedAndUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_AND.
uint2 NvInterlockedAndUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_AND.
uint2 NvInterlockedAndUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_AND.
uint2 NvInterlockedAndUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_AND.
uint2 NvInterlockedCompareExchangeUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 compare_value, uint2 value)
References __NvAtomicCompareExchangeUINT64().
uint2 NvInterlockedCompareExchangeUint64 (RWTexture1D< uint2 > uav, uint address, uint2 compare_value, uint2 value)
References __NvAtomicCompareExchangeUINT64().
uint2 NvInterlockedCompareExchangeUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 compare_value, uint2 value)
References __NvAtomicCompareExchangeUINT64().
uint2 NvInterlockedCompareExchangeUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 compare_value, uint2 value)
References __NvAtomicCompareExchangeUINT64().
uint2 NvInterlockedExchangeUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_SWAP.
uint2 NvInterlockedExchangeUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_SWAP.
uint2 NvInterlockedExchangeUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_SWAP.
uint2 NvInterlockedExchangeUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_SWAP.
uint NvInterlockedMaxFp16x2 (RWByteAddressBuffer uav, uint byteAddress, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint NvInterlockedMaxFp16x2 (RWByteAddressBuffer uav, uint byteAddress, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint NvInterlockedMaxFp16x2 (RWTexture1D< float2 > uav, uint address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint NvInterlockedMaxFp16x2 (RWTexture2D< float2 > uav, uint2 address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint NvInterlockedMaxFp16x2 (RWTexture3D< float2 > uav, uint3 address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint NvInterlockedMaxFp16x2 (RWTexture1D< float2 > uav, uint address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint NvInterlockedMaxFp16x2 (RWTexture2D< float2 > uav, uint2 address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint NvInterlockedMaxFp16x2 (RWTexture3D< float2 > uav, uint3 address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxFp16x4 (RWTexture1D< float4 > uav, uint address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxFp16x4 (RWTexture2D< float4 > uav, uint2 address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxFp16x4 (RWTexture3D< float4 > uav, uint3 address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxFp16x4 (RWTexture1D< float4 > uav, uint address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxFp16x4 (RWTexture2D< float4 > uav, uint2 address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxFp16x4 (RWTexture3D< float4 > uav, uint3 address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_MAX.
uint2 NvInterlockedMaxUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_MAX.
uint NvInterlockedMinFp16x2 (RWByteAddressBuffer uav, uint byteAddress, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint NvInterlockedMinFp16x2 (RWByteAddressBuffer uav, uint byteAddress, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint NvInterlockedMinFp16x2 (RWTexture1D< float2 > uav, uint address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint NvInterlockedMinFp16x2 (RWTexture2D< float2 > uav, uint2 address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint NvInterlockedMinFp16x2 (RWTexture3D< float2 > uav, uint3 address, uint fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint NvInterlockedMinFp16x2 (RWTexture1D< float2 > uav, uint address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint NvInterlockedMinFp16x2 (RWTexture2D< float2 > uav, uint2 address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint NvInterlockedMinFp16x2 (RWTexture3D< float2 > uav, uint3 address, float2 val)
References __fp32x2Tofp16x2(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinFp16x4 (RWTexture1D< float4 > uav, uint address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinFp16x4 (RWTexture2D< float4 > uav, uint2 address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinFp16x4 (RWTexture3D< float4 > uav, uint3 address, uint2 fp16x2Val)
References __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinFp16x4 (RWTexture1D< float4 > uav, uint address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinFp16x4 (RWTexture2D< float4 > uav, uint2 address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinFp16x4 (RWTexture3D< float4 > uav, uint3 address, float4 val)
References __fp32x4Tofp16x4(), __NvAtomicOpFP16x2(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedMinUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_MIN.
uint2 NvInterlockedOrUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_OR.
uint2 NvInterlockedOrUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_OR.
uint2 NvInterlockedOrUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_OR.
uint2 NvInterlockedOrUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_OR.
uint2 NvInterlockedXorUint64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_XOR.
uint2 NvInterlockedXorUint64 (RWTexture1D< uint2 > uav, uint address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_XOR.
uint2 NvInterlockedXorUint64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_XOR.
uint2 NvInterlockedXorUint64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value)
References __NvAtomicOpUINT64(), and NV_EXTN_ATOM_XOR.
int NvShfl (int val, uint srcLane, int width = NV_WARP_SIZE)
References __NvGetShflMaskFromWidth(), g_NvidiaExt, and NV_EXTN_OP_SHFL.
Referenced by NvShfl(), NvWaveMultiPrefixExclusiveAdd(), NvWaveMultiPrefixExclusiveAnd(), NvWaveMultiPrefixExclusiveOr(), NvWaveMultiPrefixExclusiveXOr(), NvWaveMultiPrefixInclusiveAdd(), NvWaveMultiPrefixInclusiveAnd(), NvWaveMultiPrefixInclusiveOr(), and NvWaveMultiPrefixInclusiveXOr().
int2 NvShfl (int2 val, uint srcLane, int width = NV_WARP_SIZE)
References NvShfl().
int4 NvShfl (int4 val, uint srcLane, int width = NV_WARP_SIZE)
References NvShfl().
int NvShflDown (int val, uint delta, int width = NV_WARP_SIZE)
References __NvGetShflMaskFromWidth(), g_NvidiaExt, and NV_EXTN_OP_SHFL_DOWN.
int NvShflUp (int val, uint delta, int width = NV_WARP_SIZE)
References g_NvidiaExt, NV_EXTN_OP_SHFL_UP, and NV_WARP_SIZE.
int NvShflXor (int val, uint laneMask, int width = NV_WARP_SIZE)
References __NvGetShflMaskFromWidth(), g_NvidiaExt, and NV_EXTN_OP_SHFL_XOR.
uint NvWaveMatch (uint value)
References g_NvidiaExt, and NV_EXTN_OP_MATCH_ANY.
uint NvWaveMatch (uint2 value)
References g_NvidiaExt, and NV_EXTN_OP_MATCH_ANY.
uint NvWaveMatch (uint4 value)
References g_NvidiaExt, and NV_EXTN_OP_MATCH_ANY.
uint NvWaveMatch (float value)
References g_NvidiaExt, and NV_EXTN_OP_MATCH_ANY.
uint NvWaveMatch (float2 value)
References g_NvidiaExt, and NV_EXTN_OP_MATCH_ANY.
uint NvWaveMatch (float4 value)
References g_NvidiaExt, and NV_EXTN_OP_MATCH_ANY.
uint NvWaveMultiPrefixExclusiveAdd (uint val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveAdd().
uint2 NvWaveMultiPrefixExclusiveAdd (uint2 val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveAdd().
uint4 NvWaveMultiPrefixExclusiveAdd (uint4 val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveAdd().
uint NvWaveMultiPrefixExclusiveAnd (uint val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveAnd().
uint2 NvWaveMultiPrefixExclusiveAnd (uint2 val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveAnd().
uint4 NvWaveMultiPrefixExclusiveAnd (uint4 val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveAnd().
uint NvWaveMultiPrefixExclusiveOr (uint val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveOr().
uint2 NvWaveMultiPrefixExclusiveOr (uint2 val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveOr().
uint4 NvWaveMultiPrefixExclusiveOr (uint4 val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveOr().
uint NvWaveMultiPrefixExclusiveXOr (uint val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveXOr().
uint2 NvWaveMultiPrefixExclusiveXOr (uint2 val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveXOr().
uint4 NvWaveMultiPrefixExclusiveXOr (uint4 val, uint mask)
References __NvGetSpecial(), NV_SPECIALOP_THREADLTMASK, NvActiveThreads(), NvShfl(), and NvWaveMultiPrefixInclusiveXOr().
uint NvWaveMultiPrefixInclusiveAdd (uint val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
Referenced by NvWaveMultiPrefixExclusiveAdd().
uint2 NvWaveMultiPrefixInclusiveAdd (uint2 val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
uint4 NvWaveMultiPrefixInclusiveAdd (uint4 val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
uint NvWaveMultiPrefixInclusiveAnd (uint val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
Referenced by NvWaveMultiPrefixExclusiveAnd().
uint2 NvWaveMultiPrefixInclusiveAnd (uint2 val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
uint4 NvWaveMultiPrefixInclusiveAnd (uint4 val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
uint NvWaveMultiPrefixInclusiveOr (uint val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
Referenced by NvWaveMultiPrefixExclusiveOr().
uint2 NvWaveMultiPrefixInclusiveOr (uint2 val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
uint4 NvWaveMultiPrefixInclusiveOr (uint4 val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
uint NvWaveMultiPrefixInclusiveXOr (uint val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
Referenced by NvWaveMultiPrefixExclusiveXOr().
uint2 NvWaveMultiPrefixInclusiveXOr (uint2 val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
uint4 NvWaveMultiPrefixInclusiveXOr (uint4 val, uint mask)
References __NvGetSpecial(), __NvShflGeneric(), NV_SPECIALOP_THREADLTMASK, NV_WARP_SIZE_LOG2, NvActiveThreads(), and NvShfl().
Copyright (c) 2007-2019 NVIDIA Corporation. All rights reserved.