NVAPI Reference Documentation
NVAPI Reference Documentation
NVIDIA
Release 440: November 15
2019
nvHLSLExtnsInternal.h File Reference
#include "nvShaderExtnEnums.h"
Data Structures
struct NvShaderExtnStruct
Macros
#define NV_EXTN_ATOM_AND 0
#define NV_EXTN_ATOM_OR 1
#define NV_EXTN_ATOM_XOR 2
#define NV_EXTN_ATOM_ADD 3
#define NV_EXTN_ATOM_MAX 6
#define NV_EXTN_ATOM_MIN 7
#define NV_EXTN_ATOM_SWAP 8
#define NV_EXTN_ATOM_CAS 9
Functions
int __NvGetShflMaskFromWidth (uint width)
void __NvReferenceUAVForOp (RWByteAddressBuffer uav)
void __NvReferenceUAVForOp (RWTexture1D< float2 > uav)
void __NvReferenceUAVForOp (RWTexture2D< float2 > uav)
void __NvReferenceUAVForOp (RWTexture3D< float2 > uav)
void __NvReferenceUAVForOp (RWTexture1D< float4 > uav)
void __NvReferenceUAVForOp (RWTexture2D< float4 > uav)
void __NvReferenceUAVForOp (RWTexture3D< float4 > uav)
void __NvReferenceUAVForOp (RWTexture1D< float > uav)
void __NvReferenceUAVForOp (RWTexture2D< float > uav)
void __NvReferenceUAVForOp (RWTexture3D< float > uav)
void __NvReferenceUAVForOp (RWTexture1D< uint2 > uav)
void __NvReferenceUAVForOp (RWTexture2D< uint2 > uav)
void __NvReferenceUAVForOp (RWTexture3D< uint2 > uav)
void __NvReferenceUAVForOp (RWTexture1D< uint4 > uav)
void __NvReferenceUAVForOp (RWTexture2D< uint4 > uav)
void __NvReferenceUAVForOp (RWTexture3D< uint4 > uav)
void __NvReferenceUAVForOp (RWTexture1D< uint > uav)
void __NvReferenceUAVForOp (RWTexture2D< uint > uav)
void __NvReferenceUAVForOp (RWTexture3D< uint > uav)
void __NvReferenceUAVForOp (RWTexture1D< int2 > uav)
void __NvReferenceUAVForOp (RWTexture2D< int2 > uav)
void __NvReferenceUAVForOp (RWTexture3D< int2 > uav)
void __NvReferenceUAVForOp (RWTexture1D< int4 > uav)
void __NvReferenceUAVForOp (RWTexture2D< int4 > uav)
void __NvReferenceUAVForOp (RWTexture3D< int4 > uav)
void __NvReferenceUAVForOp (RWTexture1D< int > uav)
void __NvReferenceUAVForOp (RWTexture2D< int > uav)
void __NvReferenceUAVForOp (RWTexture3D< int > uav)
uint __NvAtomicOpFP16x2 (RWByteAddressBuffer uav, uint byteAddress, uint fp16x2Val, uint atomicOpType)
uint __NvAtomicOpFP16x2 (RWTexture1D< float2 > uav, uint address, uint fp16x2Val, uint atomicOpType)
uint __NvAtomicOpFP16x2 (RWTexture2D< float2 > uav, uint2 address, uint fp16x2Val, uint atomicOpType)
uint __NvAtomicOpFP16x2 (RWTexture3D< float2 > uav, uint3 address, uint fp16x2Val, uint atomicOpType)
uint2 __NvAtomicOpFP16x2 (RWTexture1D< float4 > uav, uint address, uint2 fp16x2Val, uint atomicOpType)
uint2 __NvAtomicOpFP16x2 (RWTexture2D< float4 > uav, uint2 address, uint2 fp16x2Val, uint atomicOpType)
uint2 __NvAtomicOpFP16x2 (RWTexture3D< float4 > uav, uint3 address, uint2 fp16x2Val, uint atomicOpType)
uint __fp32x2Tofp16x2 (float2 val)
uint2 __fp32x4Tofp16x4 (float4 val)
float __NvAtomicAddFP32 (RWByteAddressBuffer uav, uint byteAddress, float val)
float __NvAtomicAddFP32 (RWTexture1D< float > uav, uint address, float val)
float __NvAtomicAddFP32 (RWTexture2D< float > uav, uint2 address, float val)
float __NvAtomicAddFP32 (RWTexture3D< float > uav, uint3 address, float val)
uint2 __NvAtomicCompareExchangeUINT64 (RWByteAddressBuffer uav, uint byteAddress, uint2 compareValue, uint2 value)
uint2 __NvAtomicOpUINT64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value, uint atomicOpType)
uint2 __NvAtomicCompareExchangeUINT64 (RWTexture1D< uint2 > uav, uint address, uint2 compareValue, uint2 value)
uint2 __NvAtomicOpUINT64 (RWTexture1D< uint2 > uav, uint address, uint2 value, uint atomicOpType)
uint2 __NvAtomicCompareExchangeUINT64 (RWTexture2D< uint2 > uav, uint2 address, uint2 compareValue, uint2 value)
uint2 __NvAtomicOpUINT64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value, uint atomicOpType)
uint2 __NvAtomicCompareExchangeUINT64 (RWTexture3D< uint2 > uav, uint3 address, uint2 compareValue, uint2 value)
uint2 __NvAtomicOpUINT64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value, uint atomicOpType)
uint4 __NvFootprint (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint footprintmode, uint gran, int3 offset=int3(0, 0, 0))
uint4 __NvFootprintBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint footprintmode, uint gran, float bias, int3 offset=int3(0, 0, 0))
uint4 __NvFootprintLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint footprintmode, uint gran, float lodLevel, int3 offset=int3(0, 0, 0))
uint4 __NvFootprintGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint footprintmode, uint gran, float3 ddx, float3 ddy, int3 offset=int3(0, 0, 0))
uint __NvGetSpecial (uint subOpCode)
int __NvShflGeneric (int val, uint srcLane, uint maskClampVal, out uint laneValid)
Variables
RWStructuredBuffer< NvShaderExtnStruct > g_NvidiaExt
Macro Definition Documentation
#define NV_EXTN_ATOM_ADD 3
Referenced by __NvAtomicAddFP32(), NvInterlockedAddFp16x2(), NvInterlockedAddFp16x4(), and NvInterlockedAddUint64().
#define NV_EXTN_ATOM_AND 0
Referenced by NvInterlockedAndUint64().
#define NV_EXTN_ATOM_CAS 9
Referenced by __NvAtomicCompareExchangeUINT64().
#define NV_EXTN_ATOM_MAX 6
Referenced by NvInterlockedMaxFp16x2(), NvInterlockedMaxFp16x4(), and NvInterlockedMaxUint64().
#define NV_EXTN_ATOM_MIN 7
Referenced by NvInterlockedMinFp16x2(), NvInterlockedMinFp16x4(), and NvInterlockedMinUint64().
#define NV_EXTN_ATOM_OR 1
Referenced by NvInterlockedOrUint64().
#define NV_EXTN_ATOM_SWAP 8
Referenced by NvInterlockedExchangeUint64().
#define NV_EXTN_ATOM_XOR 2
Referenced by NvInterlockedXorUint64().
Function Documentation
uint __fp32x2Tofp16x2 (float2 val)
Referenced by NvInterlockedAddFp16x2(), NvInterlockedMaxFp16x2(), and NvInterlockedMinFp16x2().
uint2 __fp32x4Tofp16x4 (float4 val)
Referenced by NvInterlockedAddFp16x4(), NvInterlockedMaxFp16x4(), and NvInterlockedMinFp16x4().
float __NvAtomicAddFP32 (RWByteAddressBuffer uav, uint byteAddress, float val)
References __NvReferenceUAVForOp(), NvShaderExtnStruct::dst0u, g_NvidiaExt, NV_EXTN_ATOM_ADD, and NV_EXTN_OP_FP32_ATOMIC.
Referenced by NvInterlockedAddFp32().
float __NvAtomicAddFP32 (RWTexture1D< float > uav, uint address, float val)
References __NvReferenceUAVForOp(), NvShaderExtnStruct::dst0u, g_NvidiaExt, NV_EXTN_ATOM_ADD, and NV_EXTN_OP_FP32_ATOMIC.
float __NvAtomicAddFP32 (RWTexture2D< float > uav, uint2 address, float val)
References __NvReferenceUAVForOp(), NvShaderExtnStruct::dst0u, g_NvidiaExt, NV_EXTN_ATOM_ADD, and NV_EXTN_OP_FP32_ATOMIC.
float __NvAtomicAddFP32 (RWTexture3D< float > uav, uint3 address, float val)
References __NvReferenceUAVForOp(), NvShaderExtnStruct::dst0u, g_NvidiaExt, NV_EXTN_ATOM_ADD, and NV_EXTN_OP_FP32_ATOMIC.
uint2 __NvAtomicCompareExchangeUINT64 (RWByteAddressBuffer uav, uint byteAddress, uint2 compareValue, uint2 value)
References __NvReferenceUAVForOp(), g_NvidiaExt, NV_EXTN_ATOM_CAS, and NV_EXTN_OP_UINT64_ATOMIC.
Referenced by NvInterlockedCompareExchangeUint64().
uint2 __NvAtomicCompareExchangeUINT64 (RWTexture1D< uint2 > uav, uint address, uint2 compareValue, uint2 value)
References __NvReferenceUAVForOp(), g_NvidiaExt, NV_EXTN_ATOM_CAS, and NV_EXTN_OP_UINT64_ATOMIC.
uint2 __NvAtomicCompareExchangeUINT64 (RWTexture2D< uint2 > uav, uint2 address, uint2 compareValue, uint2 value)
References __NvReferenceUAVForOp(), g_NvidiaExt, NV_EXTN_ATOM_CAS, and NV_EXTN_OP_UINT64_ATOMIC.
uint2 __NvAtomicCompareExchangeUINT64 (RWTexture3D< uint2 > uav, uint3 address, uint2 compareValue, uint2 value)
References __NvReferenceUAVForOp(), g_NvidiaExt, NV_EXTN_ATOM_CAS, and NV_EXTN_OP_UINT64_ATOMIC.
uint __NvAtomicOpFP16x2 (RWByteAddressBuffer uav, uint byteAddress, uint fp16x2Val, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_FP16_ATOMIC.
Referenced by NvInterlockedAddFp16x2(), NvInterlockedAddFp16x4(), NvInterlockedMaxFp16x2(), NvInterlockedMaxFp16x4(), NvInterlockedMinFp16x2(), and NvInterlockedMinFp16x4().
uint __NvAtomicOpFP16x2 (RWTexture1D< float2 > uav, uint address, uint fp16x2Val, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_FP16_ATOMIC.
uint __NvAtomicOpFP16x2 (RWTexture2D< float2 > uav, uint2 address, uint fp16x2Val, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_FP16_ATOMIC.
uint __NvAtomicOpFP16x2 (RWTexture3D< float2 > uav, uint3 address, uint fp16x2Val, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_FP16_ATOMIC.
uint2 __NvAtomicOpFP16x2 (RWTexture1D< float4 > uav, uint address, uint2 fp16x2Val, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_FP16_ATOMIC.
uint2 __NvAtomicOpFP16x2 (RWTexture2D< float4 > uav, uint2 address, uint2 fp16x2Val, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_FP16_ATOMIC.
uint2 __NvAtomicOpFP16x2 (RWTexture3D< float4 > uav, uint3 address, uint2 fp16x2Val, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_FP16_ATOMIC.
uint2 __NvAtomicOpUINT64 (RWByteAddressBuffer uav, uint byteAddress, uint2 value, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_UINT64_ATOMIC.
Referenced by NvInterlockedAddUint64(), NvInterlockedAndUint64(), NvInterlockedExchangeUint64(), NvInterlockedMaxUint64(), NvInterlockedMinUint64(), NvInterlockedOrUint64(), and NvInterlockedXorUint64().
uint2 __NvAtomicOpUINT64 (RWTexture1D< uint2 > uav, uint address, uint2 value, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_UINT64_ATOMIC.
uint2 __NvAtomicOpUINT64 (RWTexture2D< uint2 > uav, uint2 address, uint2 value, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_UINT64_ATOMIC.
uint2 __NvAtomicOpUINT64 (RWTexture3D< uint2 > uav, uint3 address, uint2 value, uint atomicOpType)
References __NvReferenceUAVForOp(), g_NvidiaExt, and NV_EXTN_OP_UINT64_ATOMIC.
uint4 __NvFootprint (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint footprintmode, uint gran, int3 offset = int3(0, 0, 0))
References g_NvidiaExt, and NV_EXTN_OP_FOOTPRINT.
Referenced by NvFootprintCoarse(), and NvFootprintFine().
uint4 __NvFootprintBias (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint footprintmode, uint gran, float bias, int3 offset = int3(0, 0, 0))
References g_NvidiaExt, and NV_EXTN_OP_FOOTPRINT_BIAS.
Referenced by NvFootprintCoarseBias(), and NvFootprintFineBias().
uint4 __NvFootprintGrad (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint footprintmode, uint gran, float3 ddx, float3 ddy, int3 offset = int3(0, 0, 0))
References g_NvidiaExt, and NV_EXTN_OP_FOOTPRINT_GRAD.
Referenced by NvFootprintCoarseGrad(), and NvFootprintFineGrad().
uint4 __NvFootprintLevel (uint texSpace, uint texIndex, uint smpSpace, uint smpIndex, uint texType, float3 location, uint footprintmode, uint gran, float lodLevel, int3 offset = int3(0, 0, 0))
References g_NvidiaExt, and NV_EXTN_OP_FOOTPRINT_LEVEL.
Referenced by NvFootprintCoarseLevel(), and NvFootprintFineLevel().
int __NvGetShflMaskFromWidth (uint width)
References NV_WARP_SIZE.
Referenced by NvShfl(), NvShflDown(), and NvShflXor().
uint __NvGetSpecial (uint subOpCode)
References g_NvidiaExt, and NV_EXTN_OP_GET_SPECIAL.
Referenced by NvFootprintCoarse(), NvFootprintCoarseBias(), NvFootprintCoarseGrad(), NvFootprintCoarseLevel(), NvFootprintFine(), NvFootprintFineBias(), NvFootprintFineGrad(), NvFootprintFineLevel(), NvGetSpecial(), NvWaveMultiPrefixExclusiveAdd(), NvWaveMultiPrefixExclusiveAnd(), NvWaveMultiPrefixExclusiveOr(), NvWaveMultiPrefixExclusiveXOr(), NvWaveMultiPrefixInclusiveAdd(), NvWaveMultiPrefixInclusiveAnd(), NvWaveMultiPrefixInclusiveOr(), and NvWaveMultiPrefixInclusiveXOr().
void __NvReferenceUAVForOp (RWByteAddressBuffer uav)
References g_NvidiaExt.
Referenced by __NvAtomicAddFP32(), __NvAtomicCompareExchangeUINT64(), __NvAtomicOpFP16x2(), and __NvAtomicOpUINT64().
void __NvReferenceUAVForOp (RWTexture1D< float2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< float2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< float2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture1D< float4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< float4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< float4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture1D< float > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< float > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< float > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture1D< uint2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< uint2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< uint2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture1D< uint4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< uint4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< uint4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture1D< uint > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< uint > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< uint > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture1D< int2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< int2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< int2 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture1D< int4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< int4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< int4 > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture1D< int > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture2D< int > uav)
References g_NvidiaExt.
void __NvReferenceUAVForOp (RWTexture3D< int > uav)
References g_NvidiaExt.
int __NvShflGeneric (int val, uint srcLane, uint maskClampVal, out uint laneValid)
References g_NvidiaExt, and NV_EXTN_OP_SHFL_GENERIC.
Referenced by NvWaveMultiPrefixInclusiveAdd(), NvWaveMultiPrefixInclusiveAnd(), NvWaveMultiPrefixInclusiveOr(), and NvWaveMultiPrefixInclusiveXOr().
Variable Documentation
RWStructuredBuffer<NvShaderExtnStruct> g_NvidiaExt
Referenced by __NvAtomicAddFP32(), __NvAtomicCompareExchangeUINT64(), __NvAtomicOpFP16x2(), __NvAtomicOpUINT64(), __NvFootprint(), __NvFootprintBias(), __NvFootprintGrad(), __NvFootprintLevel(), __NvGetSpecial(), __NvReferenceUAVForOp(), __NvShflGeneric(), NvAll(), NvAny(), NvBallot(), NvEvaluateAttributeAtSampleForVPRS(), NvEvaluateAttributeSnappedForVPRS(), NvGetLaneId(), NvGetShadingRate(), NvShfl(), NvShflDown(), NvShflUp(), NvShflXor(), and NvWaveMatch().
Copyright (c) 2007-2019 NVIDIA Corporation. All rights reserved.